function createfigure(yvector1)
%CREATEFIGURE(YVECTOR1)
%  YVECTOR1:  bar yvector

%  Auto-generated by MATLAB on 23-Sep-2015 16:29:15

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'XTick',[1 2 3]);
box(axes1,'on');
hold(axes1,'on');

% Create bar
bar(yvector1);

